<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "sponsoring"
 *
 * Auto generated by Extension Builder 2015-11-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Sponsoring',
    'description' => 'Display sponsoring projects',
    'category' => 'plugin',
    'author' => 'Stefan Frömken',
    'author_email' => 'projects@jweiland.net',
    'state' => 'stable',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
            'maps2' => '3.0.0-3.9.99',
            'service_bw2' => '0.0.1-1.99.99'
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
