categories:
  sponsoring:
    label: 'sponsoring'
  sponsoring.templates:
    label: 'Templates'
    parent: sponsoring
  sponsoring.pages:
    label: 'Pages'
    parent: sponsoring
  sponsoring.settings:
    label: 'Settings'
    parent: sponsoring
settings:
  sponsoring.templateRootPath:
    label: 'Templates'
    category: sponsoring.templates
    description: 'Path to template root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Templates/'
  sponsoring.partialRootPath:
    label: 'Partials'
    category: sponsoring.templates
    description: 'Path to partial root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Partials/'
  sponsoring.layoutRootPath:
    label: 'Layouts'
    category: sponsoring.templates
    description: 'Path to layout root'
    type: string
    default: 'EXT:sponsoring/Resources/Private/Layouts/'
  sponsoring.storagePid:
    label: 'Default storage PID'
    category: sponsoring.settings
    description: 'Folder that stores all POIs'
    type: int
    default: 0
  sponsoring.pidOfMaps2Plugin:
    label: 'Pid of Maps Page'
    category: 'sponsoring.pages'
    description: 'Page UID with Maps2 records'
    type: int
    default: 0
  sponsoring.pidOfDetailPage:
    label: 'Pid of Detail Page'
    category: 'sponsoring.pages'
    description: 'Page UID of Detail Page'
    type: int
    default: 0
  sponsoring.pidOfServiceBw2Page:
    label: 'Pid of ServiceBw2 Page'
    category: 'sponsoring.pages'
    description: 'Page UID with ServiceBw2 records'
    type: int
    default: 0
  sponsoring.pageBrowser.itemsPerPage:
    label: 'Items per page for pagination'
    category: 'sponsoring.settings'
    description: 'Number of results that needs to be shown on listing page'
    type: int
    default: 15
